# Generated by Django 2.2.7 on 2019-11-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
