# Generated by Django 2.2.7 on 2019-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0002_auto_20191114_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
